export const COURSE_SEED_DATA = [
  {
    code: '10100214',
    titleTh: 'เกษตรเพื่อชีวิต',
    titleEn: 'Agriculture for Life',
    description:
      'หมวดวิชาศึกษาทั่วไป กลุ่มคุณค่าความเป็นมนุษย์และการใช้ชีวิต (ELO 2)',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700301',
    titleTh: 'ภาษาไทยเพื่อการนำเสนอ',
    titleEn: 'Thai for Presentation',
    description:
      'หมวดวิชาศึกษาทั่วไป กลุ่มวิชาภาษาและการสื่อสาร (ELO 3) รายวิชาภาษาไทย',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700308',
    titleTh: 'ภาษาอังกฤษในชีวิตประจำวัน',
    titleEn: 'English in Everyday Life',
    description:
      'หมวดวิชาศึกษาทั่วไป กลุ่มวิชาภาษาและการสื่อสาร (ELO 3) รายวิชาภาษาต่างประเทศ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301113',
    titleTh: 'คณิตศาสตร์ดีสครีต',
    titleEn: 'Discrete Mathematics',
    description: '',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10800113',
    titleTh: 'พลเมืองดิจิทัล',
    titleEn: 'Digital Citizenship',
    description: 'หมวดวิชาศึกษาทั่วไป กลุ่มวิชาสังคมและวัฒนธรรม (ELO 1)',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700309',
    titleTh: 'สนทนาภาษาอังกฤษ',
    titleEn: 'English Conversation',
    description:
      'หมวดวิชาศึกษาทั่วไป กลุ่มวิชาภาษาและการสื่อสาร (ELO 3) รายวิชาภาษาต่างประเทศ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700313',
    titleTh: 'ภาษาอังกฤษเชิงวิทยาศาสตร์และนวัตกรรม',
    titleEn: 'English for Science and Innovation',
    description: 'หมวดวิชาศึกษาทั่วไป กลุ่มวิชาภาษาและการสื่อสาร (ELO 3)',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10304205',
    titleTh: 'ความน่าจะเป็นและสถิติ',
    titleEn: 'Probability and Statistics',
    description: '',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700105',
    titleTh: 'มนุษย์ สังคม เทคโนโลยีและสิ่งแวดล้อม',
    titleEn: 'Man, Society, Technology and Environment',
    description: 'หมวดวิชาศึกษาทั่วไป กลุ่มวิชาสังคมและวัฒนธรรม (ELO 1)',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700320',
    titleTh: 'ภาษาอังกฤษเพื่อการศึกษาต่อและการประกอบอาชีพ',
    titleEn: 'English for Further Study and Careers',
    description:
      'หมวดวิชาศึกษาทั่วไป กลุ่มวิชาภาษาและการสื่อสาร (ELO 3) รายวิชาภาษาต่างประเทศ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300411',
    titleTh: 'วิทยาศาสตร์เพื่อชีวิต',
    titleEn: 'Science for Life',
    description:
      'หมวดวิชาศึกษาทั่วไป กลุ่มการคิดคำนวณการใช้เหตุผลและเทคโนโลยี (ELO 4) ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301491',
    titleTh: 'สัมมนาวิชาการทางวิทยาการคอมพิวเตอร์',
    titleEn: 'Seminar in Computer Science',
    description: '',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10300410',
    titleTh: 'ความฉลาดรู้ด้านวิทยาศาสตร์สำหรับโลกสมัยใหม่',
    titleEn: 'Scientific Literacy for the Modern World',
    description:
      'หมวดวิชาศึกษาทั่วไป กลุ่มการคิดคำนวณการใช้เหตุผลและเทคโนโลยี (ELO 4)',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10200504',
    titleTh: 'การเป็นผู้ประกอบการ',
    titleEn: 'Entrepreneurship',
    description: 'หมวดวิชาศึกษาทั่วไป กลุ่มการเป็นผู้ประกอบการ (ELO 5)',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300497',
    titleTh: 'สหกิจศึกษา',
    titleEn: 'Cooperative Education',
    description: '',
    credits: 0,
    lectureHours: 0,
    labHours: 0,
    selfStudyHours: 0,
    isActive: true,
  },
  {
    code: '10300498',
    titleTh: 'การเรียนรู้อิสระ',
    titleEn: 'Independent Study',
    description: '',
    credits: 0,
    lectureHours: 0,
    labHours: 0,
    selfStudyHours: 0,
    isActive: true,
  },
  {
    code: '10300499',
    titleTh: 'การศึกษา หรือ ฝึกงาน หรือฝึกอบรมต่างประเทศ',
    titleEn: 'Study or Internship or Training Abroad',
    description: '',
    credits: 0,
    lectureHours: 0,
    labHours: 0,
    selfStudyHours: 0,
    isActive: true,
  },
  {
    code: '10301111',
    titleTh: 'Course 10301111',
    titleEn: 'Course 10301111',
    description: 'Placeholder for course 10301111',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10305108',
    titleTh: 'Course 10305108',
    titleEn: 'Course 10305108',
    description: 'Placeholder for course 10305108',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301211',
    titleTh: 'Course 10301211',
    titleEn: 'Course 10301211',
    description: 'Placeholder for course 10301211',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301112',
    titleTh: 'Course 10301112',
    titleEn: 'Course 10301112',
    description: 'Placeholder for course 10301112',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301114',
    titleTh: 'Course 10301114',
    titleEn: 'Course 10301114',
    description: 'Placeholder for course 10301114',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301141',
    titleTh: 'Course 10301141',
    titleEn: 'Course 10301141',
    description: 'Placeholder for course 10301141',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301212',
    titleTh: 'Course 10301212',
    titleEn: 'Course 10301212',
    description: 'Placeholder for course 10301212',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301221',
    titleTh: 'Course 10301221',
    titleEn: 'Course 10301221',
    description: 'Placeholder for course 10301221',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301222',
    titleTh: 'Course 10301222',
    titleEn: 'Course 10301222',
    description: 'Placeholder for course 10301222',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301223',
    titleTh: 'Course 10301223',
    titleEn: 'Course 10301223',
    description: 'Placeholder for course 10301223',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301224',
    titleTh: 'Course 10301224',
    titleEn: 'Course 10301224',
    description: 'Placeholder for course 10301224',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301225',
    titleTh: 'Course 10301225',
    titleEn: 'Course 10301225',
    description: 'Placeholder for course 10301225',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301231',
    titleTh: 'Course 10301231',
    titleEn: 'Course 10301231',
    description: 'Placeholder for course 10301231',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301232',
    titleTh: 'Course 10301232',
    titleEn: 'Course 10301232',
    description: 'Placeholder for course 10301232',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301233',
    titleTh: 'Course 10301233',
    titleEn: 'Course 10301233',
    description: 'Placeholder for course 10301233',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301311',
    titleTh: 'Course 10301311',
    titleEn: 'Course 10301311',
    description: 'Placeholder for course 10301311',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301312',
    titleTh: 'Course 10301312',
    titleEn: 'Course 10301312',
    description: 'Placeholder for course 10301312',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301313',
    titleTh: 'Course 10301313',
    titleEn: 'Course 10301313',
    description: 'Placeholder for course 10301313',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301314',
    titleTh: 'Course 10301314',
    titleEn: 'Course 10301314',
    description: 'Placeholder for course 10301314',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301331',
    titleTh: 'Course 10301331',
    titleEn: 'Course 10301331',
    description: 'Placeholder for course 10301331',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301332',
    titleTh: 'Course 10301332',
    titleEn: 'Course 10301332',
    description: 'Placeholder for course 10301332',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301333',
    titleTh: 'Course 10301333',
    titleEn: 'Course 10301333',
    description: 'Placeholder for course 10301333',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301334',
    titleTh: 'Course 10301334',
    titleEn: 'Course 10301334',
    description: 'Placeholder for course 10301334',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301335',
    titleTh: 'Course 10301335',
    titleEn: 'Course 10301335',
    description: 'Placeholder for course 10301335',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301336',
    titleTh: 'Course 10301336',
    titleEn: 'Course 10301336',
    description: 'Placeholder for course 10301336',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301341',
    titleTh: 'Course 10301341',
    titleEn: 'Course 10301341',
    description: 'Placeholder for course 10301341',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301342',
    titleTh: 'Course 10301342',
    titleEn: 'Course 10301342',
    description: 'Placeholder for course 10301342',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301343',
    titleTh: 'Course 10301343',
    titleEn: 'Course 10301343',
    description: 'Placeholder for course 10301343',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301344',
    titleTh: 'Course 10301344',
    titleEn: 'Course 10301344',
    description: 'Placeholder for course 10301344',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301345',
    titleTh: 'Course 10301345',
    titleEn: 'Course 10301345',
    description: 'Placeholder for course 10301345',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301346',
    titleTh: 'Course 10301346',
    titleEn: 'Course 10301346',
    description: 'Placeholder for course 10301346',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301347',
    titleTh: 'Course 10301347',
    titleEn: 'Course 10301347',
    description: 'Placeholder for course 10301347',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301351',
    titleTh: 'Course 10301351',
    titleEn: 'Course 10301351',
    description: 'Placeholder for course 10301351',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301352',
    titleTh: 'Course 10301352',
    titleEn: 'Course 10301352',
    description: 'Placeholder for course 10301352',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301353',
    titleTh: 'Course 10301353',
    titleEn: 'Course 10301353',
    description: 'Placeholder for course 10301353',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301354',
    titleTh: 'Course 10301354',
    titleEn: 'Course 10301354',
    description: 'Placeholder for course 10301354',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301355',
    titleTh: 'Course 10301355',
    titleEn: 'Course 10301355',
    description: 'Placeholder for course 10301355',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301356',
    titleTh: 'Course 10301356',
    titleEn: 'Course 10301356',
    description: 'Placeholder for course 10301356',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301357',
    titleTh: 'Course 10301357',
    titleEn: 'Course 10301357',
    description: 'Placeholder for course 10301357',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301358',
    titleTh: 'Course 10301358',
    titleEn: 'Course 10301358',
    description: 'Placeholder for course 10301358',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301361',
    titleTh: 'Course 10301361',
    titleEn: 'Course 10301361',
    description: 'Placeholder for course 10301361',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301362',
    titleTh: 'Course 10301362',
    titleEn: 'Course 10301362',
    description: 'Placeholder for course 10301362',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301363',
    titleTh: 'Course 10301363',
    titleEn: 'Course 10301363',
    description: 'Placeholder for course 10301363',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301364',
    titleTh: 'Course 10301364',
    titleEn: 'Course 10301364',
    description: 'Placeholder for course 10301364',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301365',
    titleTh: 'Course 10301365',
    titleEn: 'Course 10301365',
    description: 'Placeholder for course 10301365',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301366',
    titleTh: 'Course 10301366',
    titleEn: 'Course 10301366',
    description: 'Placeholder for course 10301366',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301367',
    titleTh: 'Course 10301367',
    titleEn: 'Course 10301367',
    description: 'Placeholder for course 10301367',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301371',
    titleTh: 'Course 10301371',
    titleEn: 'Course 10301371',
    description: 'Placeholder for course 10301371',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301372',
    titleTh: 'Course 10301372',
    titleEn: 'Course 10301372',
    description: 'Placeholder for course 10301372',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301373',
    titleTh: 'Course 10301373',
    titleEn: 'Course 10301373',
    description: 'Placeholder for course 10301373',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301374',
    titleTh: 'Course 10301374',
    titleEn: 'Course 10301374',
    description: 'Placeholder for course 10301374',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301375',
    titleTh: 'Course 10301375',
    titleEn: 'Course 10301375',
    description: 'Placeholder for course 10301375',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301376',
    titleTh: 'Course 10301376',
    titleEn: 'Course 10301376',
    description: 'Placeholder for course 10301376',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301377',
    titleTh: 'Course 10301377',
    titleEn: 'Course 10301377',
    description: 'Placeholder for course 10301377',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301378',
    titleTh: 'Course 10301378',
    titleEn: 'Course 10301378',
    description: 'Placeholder for course 10301378',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301379',
    titleTh: 'Course 10301379',
    titleEn: 'Course 10301379',
    description: 'Placeholder for course 10301379',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301381',
    titleTh: 'Course 10301381',
    titleEn: 'Course 10301381',
    description: 'Placeholder for course 10301381',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301382',
    titleTh: 'Course 10301382',
    titleEn: 'Course 10301382',
    description: 'Placeholder for course 10301382',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301383',
    titleTh: 'Course 10301383',
    titleEn: 'Course 10301383',
    description: 'Placeholder for course 10301383',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301384',
    titleTh: 'Course 10301384',
    titleEn: 'Course 10301384',
    description: 'Placeholder for course 10301384',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301385',
    titleTh: 'Course 10301385',
    titleEn: 'Course 10301385',
    description: 'Placeholder for course 10301385',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301391',
    titleTh: 'Course 10301391',
    titleEn: 'Course 10301391',
    description: 'Placeholder for course 10301391',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301392',
    titleTh: 'Course 10301392',
    titleEn: 'Course 10301392',
    description: 'Placeholder for course 10301392',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },

  // วิชาของหลักสูตรปี 2559

  // หมวดรายวิชาที่ไม่นับหน่วยกิต (ประเมินผลเป็น S/U)
  {
    code: '20314501',
    titleTh: 'ระเบียบวิธีวิจัยทางนวัตกรรมเทคโนโลยีดิจิทัล',
    titleEn: 'Research Methodology in Digital Technology Innovation',
    description: 'รายวิชาที่ไม่นับหน่วยกิต',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314591',
    titleTh: 'สัมมนา 1',
    titleEn: 'Seminar 1',
    description: 'รายวิชาที่ไม่นับหน่วยกิต',
    credits: 1,
    lectureHours: 0,
    labHours: 2,
    selfStudyHours: 1,
    isActive: true,
  },
  {
    code: '20314592',
    titleTh: 'สัมมนา 2',
    titleEn: 'Seminar 2',
    description: 'รายวิชาที่ไม่นับหน่วยกิต',
    credits: 1,
    lectureHours: 0,
    labHours: 2,
    selfStudyHours: 1,
    isActive: true,
  },
  {
    code: '20314593',
    titleTh: 'สัมมนา 3',
    titleEn: 'Seminar 3',
    description: 'รายวิชาที่ไม่นับหน่วยกิต',
    credits: 1,
    lectureHours: 0,
    labHours: 2,
    selfStudyHours: 1,
    isActive: true,
  },
  {
    code: '20314594',
    titleTh: 'สัมมนา 4',
    titleEn: 'Seminar 4',
    description: 'รายวิชาที่ไม่นับหน่วยกิต',
    credits: 1,
    lectureHours: 0,
    labHours: 2,
    selfStudyHours: 1,
    isActive: true,
  },

  // หมวดวิทยานิพนธ์
  {
    code: '20314691',
    titleTh: 'วิทยานิพนธ์ 1',
    titleEn: 'Thesis 1',
    description: 'วิทยานิพนธ์',
    credits: 6,
    lectureHours: 0,
    labHours: 18,
    selfStudyHours: 0,
    isActive: true,
  },
  {
    code: '20314692',
    titleTh: 'วิทยานิพนธ์ 2',
    titleEn: 'Thesis 2',
    description: 'วิทยานิพนธ์',
    credits: 6,
    lectureHours: 0,
    labHours: 18,
    selfStudyHours: 0,
    isActive: true,
  },
  {
    code: '20314693',
    titleTh: 'วิทยานิพนธ์ 3',
    titleEn: 'Thesis 3',
    description: 'วิทยานิพนธ์',
    credits: 12,
    lectureHours: 0,
    labHours: 36,
    selfStudyHours: 0,
    isActive: true,
  },
  {
    code: '20314694',
    titleTh: 'วิทยานิพนธ์ 4',
    titleEn: 'Thesis 4',
    description: 'วิทยานิพนธ์',
    credits: 12,
    lectureHours: 0,
    labHours: 36,
    selfStudyHours: 0,
    isActive: true,
  },

  // วิชาเอกบังคับ
  {
    code: '20314502',
    titleTh: 'แก่นนวัตกรรมเทคโนโลยีดิจิทัล',
    titleEn: 'Digital Technology Innovation Essential',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314503',
    titleTh: 'การพัฒนาแอพพลิเคชันและเซอร์วิส',
    titleEn: 'Application and Services Development',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314504',
    titleTh: 'นวัตกรรมการสื่อสารแบบครบวงจร',
    titleEn: 'Unified Communication Innovation',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },

  // วิชาเอกเลือก - กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ
  {
    code: '20314511',
    titleTh: 'วิทยาการข้อมูล',
    titleEn: 'Data Science',
    description: 'กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314512',
    titleTh: 'การเรียนรู้ของเครื่องจักรและปัญญาประดิษฐ์',
    titleEn: 'Machine Learning and Artificial Intelligence',
    description: 'กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314513',
    titleTh: 'การพัฒนานวัตกรรมเทคโนโลยีดิจิทัล',
    titleEn: 'Digital Technology Innovation Development',
    description: 'กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314514',
    titleTh: 'การพัฒนาแอพพลิเคชันบนอุปกรณ์อัจฉริยะ',
    titleEn: 'Smart Devices Application Development',
    description: 'กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314515',
    titleTh: 'การค้นคืนสารสนเทศ',
    titleEn: 'Information Retrieval',
    description: 'กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314516',
    titleTh: 'การประมวลผลเชิงมัลติมีเดีย',
    titleEn: 'Multimedia Processing',
    description: 'กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314517',
    titleTh: 'นวัตกรรมภูมิสารสนเทศเกษตร',
    titleEn: 'Agricultural Geo-informatics Innovation',
    description: 'กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314518',
    titleTh: 'การประมวลผลบนกลุ่มเมฆขั้นสูง',
    titleEn: 'Advanced Cloud Computing',
    description: 'กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314519',
    titleTh: 'หัวข้อที่สนใจทางนวัตกรรมเทคโนโลยีดิจิทัล 1',
    titleEn: 'Selected Topics in Digital Technology Innovation 1',
    description: 'กลุ่มวิชาพัฒนาระบบสารสนเทศอัจฉริยะ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },

  // วิชาเอกเลือก - กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้
  {
    code: '20314521',
    titleTh: 'การคิดเชิงนวัตกรรมเพื่อการเรียนรู้ดิจิทัล',
    titleEn: 'Innovative Thinking for Digital Learning',
    description: 'กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '20314522',
    titleTh: 'นวัตกรรมเทคโนโลยีดิจิทัลเพื่อการศึกษา',
    titleEn: 'Digital Technology Innovation for Education',
    description: 'กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314523',
    titleTh: 'นวัตกรรมเทคโนโลยีดิจิทัลเพื่อพัฒนากระบวนการเรียนรู้',
    titleEn:
      'Digital Technology Innovation for Development of Learning Process',
    description: 'กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314524',
    titleTh: 'การผลิตสื่อดิจิทัลอัจฉริยะเพื่อการเรียนรู้',
    titleEn: 'Smart Digital Media Production for Learning',
    description: 'กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314525',
    titleTh: 'นวัตกรรมการเรียนรู้ดิจิทัลในชุมชนออนไลน์',
    titleEn: 'Digital Learning Innovation in Online Communities',
    description: 'กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314526',
    titleTh: 'การจัดการความรู้ในนวัตกรรมเทคโนโลยีดิจิทัล',
    titleEn: 'Knowledge Management in Digital Technology Innovation',
    description: 'กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314527',
    titleTh: 'การจำลองระบบและการสร้างตัวแบบข้อมูล',
    titleEn: 'System Simulation and Data Modeling',
    description: 'กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314528',
    titleTh: 'อนาคตศึกษาในการเรียนรู้ดิจิทัล',
    titleEn: 'Future Studies in Digital Learning',
    description: 'กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314529',
    titleTh: 'หัวข้อที่สนใจทางนวัตกรรมเทคโนโลยีดิจิทัล 2',
    titleEn: 'Selected Topics in Digital Technology Innovation 2',
    description: 'กลุ่มวิชานวัตกรรมดิจิทัลเพื่อการเรียนรู้',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },

  // วิชาเอกเลือก - กลุ่มวิชาบริหารจัดการนวัตกรรม
  {
    code: '20314531',
    titleTh: 'การจัดการกระบวนการนวัตกรรม',
    titleEn: 'Innovation Process Management',
    description: 'กลุ่มวิชาบริหารจัดการนวัตกรรม',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314532',
    titleTh: 'นวัตกรรมสีเขียว',
    titleEn: 'Green Innovation',
    description: 'กลุ่มวิชาบริหารจัดการนวัตกรรม',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314533',
    titleTh: 'ทักษะการเป็นผู้ประกอบการนวัตกรรมดิจิทัล',
    titleEn: 'Digital Innopreneur Skill',
    description: 'กลุ่มวิชาบริหารจัดการนวัตกรรม',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314534',
    titleTh: 'การจัดการตลาดสินค้าดิจิทัล',
    titleEn: 'Digital Marketing Management',
    description: 'กลุ่มวิชาบริหารจัดการนวัตกรรม',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314535',
    titleTh: 'บริหารจัดการโครงการนวัตกรรม',
    titleEn: 'Innovation Project Management',
    description: 'กลุ่มวิชาบริหารจัดการนวัตกรรม',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314536',
    titleTh: 'การจัดการนวัตกรรมทางห่วงโซ่อุปทานและโลจิสติกส์',
    titleEn: 'Innovation Management in Supply Chain and Logistic',
    description: 'กลุ่มวิชาบริหารจัดการนวัตกรรม',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314537',
    titleTh: 'โมเดลธุรกิจอัจฉริยะ',
    titleEn: 'Business Intelligence Model',
    description: 'กลุ่มวิชาบริหารจัดการนวัตกรรม',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314538',
    titleTh: 'นวัตกรรมทางธุรกิจ',
    titleEn: 'Innovation in Business',
    description: 'กลุ่มวิชาบริหารจัดการนวัตกรรม',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '20314539',
    titleTh: 'หัวข้อที่สนใจทางนวัตกรรมเทคโนโลยีดิจิทัล 3',
    titleEn: 'Selected Topics in Digital Technology Innovation 3',
    description: 'กลุ่มวิชาบริหารจัดการนวัตกรรม',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },

  // หลักสูตรปี 2560 (

  {
    code: 'CS111',
    titleTh: 'วิทยาการคอมพิวเตอร์ 1',
    titleEn: 'Computer Science 1',
    description: 'วิชาแกน',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS112',
    titleTh: 'วิทยาการคอมพิวเตอร์ 2',
    titleEn: 'Computer Science 2',
    description: 'วิชาแกน',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS117',
    titleTh: 'หลักการเขียนโปรแกรมเชิงวัตถุ',
    titleEn: 'Principles of Object-Oriented Programming',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS121',
    titleTh: 'ตรรกศาสตร์เชิงดิจิทัลและอุปกรณ์อัจฉริยะ',
    titleEn: 'Digital Logic and Smart Device',
    description: 'วิชาแกน',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS151',
    titleTh: 'คณิตศาสตร์ดีสครีต',
    titleEn: 'Discrete Mathematics',
    description: 'วิชาแกน',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: 'CS213',
    titleTh: 'การวิเคราะห์และออกแบบอัลกอริทึม',
    titleEn: 'Algorithm Analysis and Design',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS221',
    titleTh: 'โครงสร้างข้อมูล',
    titleEn: 'Data Structures',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS222',
    titleTh: 'การเขียนโปรแกรมมัลติมีเดีย',
    titleEn: 'Multimedia Programming',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS231',
    titleTh: 'ระบบคอมพิวเตอร์และภาษาแอสเซมบลี',
    titleEn: 'Computer System and Assembly Language',
    description: 'วิชาเอกบังคับ',
    credits: 1,
    lectureHours: 0,
    labHours: 3,
    selfStudyHours: 1,
    isActive: true,
  },
  {
    code: 'CS232',
    titleTh: 'สถาปัตยกรรมคอมพิวเตอร์',
    titleEn: 'Computer Architecture',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS241',
    titleTh: 'ระบบฐานข้อมูล',
    titleEn: 'Database Systems',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS252',
    titleTh: 'คณิตศาสตร์สำหรับวิทยาการคอมพิวเตอร์',
    titleEn: 'Mathematics for Computer Science',
    description: 'วิชาแกน',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: 'CS313',
    titleTh: 'การพัฒนาโปรแกรมประยุกต์บนเว็บ',
    titleEn: 'Web Application Development',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS320',
    titleTh: 'ระบบปฏิบัติการ',
    titleEn: 'Operating System',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS330',
    titleTh: 'การสื่อสารข้อมูลและเครือข่ายคอมพิวเตอร์',
    titleEn: 'Data Communication and Computer Network',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS341',
    titleTh: 'วิทยาการข้อมูล',
    titleEn: 'Data Science',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS343',
    titleTh: 'การวิเคราะห์และออกแบบเชิงวัตถุ',
    titleEn: 'Object Oriented Analysis and Design',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS344',
    titleTh: 'การพัฒนาระบบซอฟต์แวร์เชิงวัตถุ',
    titleEn: 'Object Oriented Software Development',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS347',
    titleTh: 'วิศวกรรมซอฟต์แวร์',
    titleEn: 'Software Engineering',
    description: 'วิชาเอกบังคับ',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS391',
    titleTh: 'การบริหารโครงการคอมพิวเตอร์',
    titleEn: 'Computer Project Management',
    description: 'วิชาเอกบังคับ',
    credits: 1,
    lectureHours: 1,
    labHours: 0,
    selfStudyHours: 2,
    isActive: true,
  },
  {
    code: 'CS392',
    titleTh: 'การเป็นผู้ประกอบการทางด้านคอมพิวเตอร์และนวัตกรรม',
    titleEn: 'Innovation and Computer-Based Entrepreneurship',
    description: 'วิชาแกน',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'CS492',
    titleTh: 'สัมมนาวิชาการทางวิทยาการคอมพิวเตอร์',
    titleEn: 'Seminar in Computer Science',
    description: 'วิชาเอกบังคับ',
    credits: 1,
    lectureHours: 0,
    labHours: 2,
    selfStudyHours: 1,
    isActive: true,
  },
  {
    code: 'GE031',
    titleTh: 'การใช้ภาษาไทย',
    titleEn: 'Thai Language Usage',
    description: 'ศึกษาทั่วไป',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'GE141',
    titleTh: 'ภาษาอังกฤษพื้นฐาน 1',
    titleEn: 'Fundamental English 1',
    description: 'ศึกษาทั่วไป',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'GE142',
    titleTh: 'ภาษาอังกฤษพื้นฐาน 2',
    titleEn: 'Fundamental English 2',
    description: 'ศึกษาทั่วไป',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'GE241',
    titleTh: 'ภาษาอังกฤษเชิงวิทยาศาสตร์และเทคโนโลยี 1',
    titleEn: 'English for Science and Technology 1',
    description: 'ศึกษาทั่วไป',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'GE242',
    titleTh: 'ภาษาอังกฤษเชิงวิทยาศาสตร์และเทคโนโลยี 2',
    titleEn: 'English for Science and Technology 2',
    description: 'ศึกษาทั่วไป',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'AP101',
    titleTh: 'เกษตรเพื่อชีวิต',
    titleEn: 'Agriculture for Life',
    description: 'ศึกษาทั่วไป',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: 'MA101',
    titleTh: 'แคลคูลัส 1',
    titleEn: 'Calculus 1',
    description: 'วิชาแกน',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: 'PH105',
    titleTh: 'ฟิสิกส์ทั่วไป 1',
    titleEn: 'General Physics 1',
    description: 'วิชาแกน',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: 'ST301',
    titleTh: 'หลักสถิติ',
    titleEn: 'Principles of Statistics',
    description: 'วิชาแกน',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: 'SC497',
    titleTh: 'สหกิจศึกษา',
    titleEn: 'Co-operative Education',
    description: 'วิชาเอกบังคับ',
    credits: 9,
    lectureHours: 0,
    labHours: 0,
    selfStudyHours: 0,
    isActive: true,
  },

  // ==========================================
  // หลักสูตรปี 2570
  // ==========================================

  // --- หมวดวิชาศึกษาทั่วไป: สมรรถนะด้านภาษาและการสื่อสาร ---
  {
    code: '10700101',
    titleTh: 'ภาษาไทยเพื่อการนำเสนอ',
    titleEn: 'Thai Language for Presentation',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านภาษาและการสื่อสาร รายวิชาภาษาไทย',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700102',
    titleTh: 'ภาษาไทยเพื่อการสื่อสาร',
    titleEn: 'Thai Language for Communication',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านภาษาและการสื่อสาร รายวิชาภาษาไทย',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700104',
    titleTh: 'ภาษาอังกฤษในชีวิตประจำวัน',
    titleEn: 'English for Everyday Life',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านภาษาและการสื่อสาร รายวิชาภาษาต่างประเทศ ระดับ A2',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700105-68',
    titleTh: 'ภาษาอังกฤษเบื้องต้นสำหรับธุรกิจและสตาร์ทอัพ',
    titleEn: 'Basic English for Business Startups',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านภาษาและการสื่อสาร รายวิชาภาษาต่างประเทศ ระดับ B1',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700106',
    titleTh: 'ภาษาอังกฤษผ่านวัฒนธรรมป๊อป',
    titleEn: 'English through Pop Culture',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านภาษาและการสื่อสาร รายวิชาภาษาต่างประเทศ ระดับ B1',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700107',
    titleTh: 'ภาษาอังกฤษเพื่อการเกษตรอัจฉริยะและยั่งยืน',
    titleEn: 'English for Smart and Sustainable Agriculture',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านภาษาและการสื่อสาร รายวิชาภาษาต่างประเทศ ระดับ B1',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700108',
    titleTh: 'สมาร์ตทอล์ก',
    titleEn: 'Smart Talk',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านภาษาและการสื่อสาร รายวิชาภาษาต่างประเทศ ระดับ B1',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },

  // --- หมวดวิชาศึกษาทั่วไป: สมรรถนะด้านสังคมและความเป็นมนุษย์ ---
  {
    code: '10100202',
    titleTh: 'วิถีเกษตรกับสุนทรียภาพในชีวิตประจำวัน',
    titleEn: 'Agri-Aesthetics and Everyday Life',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10300201',
    titleTh: 'การเงินส่วนบุคคลเพื่อชีวิตยุคใหม่',
    titleEn: 'Personal Finance for Modern Life',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700202',
    titleTh: 'จิตวิทยาการปรับตัวในยุคดิจิทัล',
    titleEn: 'Psychology of Adjustment in Digital Age',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700203',
    titleTh: 'จิตวิทยาพฤติกรรมมนุษย์',
    titleEn: 'The Psychology of Human Behavior',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700204',
    titleTh: 'จิตวิทยาเพื่อการทำงานและการดำเนินชีวิตในยุคดิจิทัล',
    titleEn: 'Psychology for Working and Living in Digital Age',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700205',
    titleTh: 'จิตอาสาเพื่อพัฒนาสังคม',
    titleEn: 'Volunteer Spirit for Social Development',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700209',
    titleTh: 'มนุษย์กับความงามทางศิลปะ',
    titleEn: 'Humans and Artistic Beauty',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700211',
    titleTh: 'ศิลปะกับความคิดสร้างสรรค์',
    titleEn: 'Art and Creative Thinking',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 1,
    labHours: 4,
    selfStudyHours: 4,
    isActive: true,
  },
  {
    code: '10700212',
    titleTh: 'ศิลปะการใช้ชีวิตในสังคมที่หลากหลาย',
    titleEn: 'The Arts of Living in a Diverse Society',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700213',
    titleTh: 'สังคมร่วมสมัย',
    titleEn: 'Contemporary World and Society',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700215',
    titleTh: 'สังคมและสิ่งแวดล้อมยั่งยืน',
    titleEn: 'Society, Environment and Sustainability',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700216',
    titleTh: 'อารยธรรมและโลกสมัยใหม่',
    titleEn: 'Civilizations and the Modern World',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10800201',
    titleTh: 'พลเมืองดิจิทัลและการรู้เท่าทันดิจิทัล',
    titleEn: 'Digital Citizenship and Digital Literacy',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านสังคมและความเป็นมนุษย์',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },

  // --- หมวดวิชาศึกษาทั่วไป: สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี ---
  {
    code: '10300301',
    titleTh: 'การใช้ชีวิตในสังคมดิจิทัล',
    titleEn: 'Living in Digital Society',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300302',
    titleTh: 'การตัดสินใจอย่างชาญฉลาดในศตวรรษที่ 21',
    titleEn: 'Intelligent Decision-Making in the 21st Century',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10300303',
    titleTh: 'ตรรกะดิจิทัลเพื่อการตัดสินใจ',
    titleEn: 'Digital Logic Approach for Decision Making',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10300304',
    titleTh: 'ถอดรหัสวิทยาศาสตร์เพื่อชีวิตยุคใหม่',
    titleEn: 'Decoding Science for Modern Life',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300305',
    titleTh: 'วิทยาศาสตร์และเทคโนโลยีลวง',
    titleEn: 'Misleading Science and Technology',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10400301',
    titleTh: 'ทักษะดิจิทัลในศตวรรษที่ 21',
    titleEn: 'Digital Skills in 21st Century',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10400303',
    titleTh: 'อาหารและเทคโนโลยี',
    titleEn: 'Food and Technology',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10800301',
    titleTh: 'จักรวาล AI',
    titleEn: 'AI Universe',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10800302',
    titleTh: 'เทคโนโลยีดิจิทัลแห่งอนาคต',
    titleEn: 'Future Digital Technologies',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการคิดคำนวณ การใช้เหตุผล และการใช้เทคโนโลยี',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },

  // --- หมวดวิชาศึกษาทั่วไป: สมรรถนะด้านการเป็นผู้ประกอบการ ---
  {
    code: '10100401',
    titleTh: 'ผู้ประกอบการนวัตกรรมด้านการผลิตพืช',
    titleEn: 'Entrepreneurship and Innovation in Plant Production',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10200401',
    titleTh: 'การตลาดบนสมาร์ทโฟน',
    titleEn: 'Marketing on Smartphone',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10200402',
    titleTh: 'การเป็นผู้ประกอบการ',
    titleEn: 'Entrepreneurship',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10200403',
    titleTh: 'ภาษีอากรสำหรับผู้ประกอบการ',
    titleEn: 'Taxation for Entrepreneurship',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10200404',
    titleTh: 'สมาร์ทไฟแนนซ์',
    titleEn: 'Smart Finance',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10200405',
    titleTh: 'เทคโนโลยีดิจิทัลสำหรับผู้ประกอบการ',
    titleEn: 'Digital Technology for Entrepreneurs',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300401',
    titleTh: 'การวางแผนธุรกิจและปัญญาประดิษฐ์สำหรับผู้ประกอบการยุคดิจิทัล',
    titleEn: 'Business Planning and Artificial Intelligence for Digital Entrepreneurs',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300402',
    titleTh: 'เทคนิคการคิดเพื่อการสร้างสรรค์นวัตกรรมสำหรับผู้ประกอบการ',
    titleEn: 'Innovative Thinking Techniques for Entrepreneurs',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300403',
    titleTh: 'วิทยาศาสตร์ในครัวเรือนสู่ไอเดียธุรกิจ',
    titleEn: 'Home-based Science to Business Ideas',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10400401',
    titleTh: 'การออกแบบชีวิตและนวัตกรรมสำหรับผู้ประกอบการ',
    titleEn: 'Life and Innovation Design for Entrepreneurs',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10400402',
    titleTh: 'ผู้ประกอบการนวัตกรรมทางการเกษตร',
    titleEn: 'Agripreneur',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10500401',
    titleTh: 'เศรษฐศาสตร์เพื่อชีวิตประจำวันและการประกอบการ',
    titleEn: 'Economics in Daily Life and Operations',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10800401',
    titleTh: 'การออกแบบแนวคิดและการสร้างแบรนด์',
    titleEn: 'Conceptualization and Brand Development',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการเป็นผู้ประกอบการ',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },

  // --- หมวดวิชาศึกษาทั่วไป: สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต ---
  {
    code: '10100501',
    titleTh: 'เกษตรเพื่อชีวิต',
    titleEn: 'Agriculture for Life',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10300502',
    titleTh: 'การสื่อสารข้อมูลเชิงเรื่องราวเพื่อการทำงานยุคใหม่',
    titleEn: 'Data Storytelling for the Modern Workplace',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300503',
    titleTh: 'โปรแกรมสำเร็จรูปเพื่อการศึกษาเพื่อการเรียนรู้ตลอดชีวิต',
    titleEn: 'Application Software for Education and Lifelong Learning',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300504',
    titleTh: 'รู้เท่าทันวิทยาศาสตร์และเทคโนโลยี: กุญแจสู่ชีวิตอนาคต',
    titleEn: 'Science & Technology Literacy: Key to the Future',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10300505',
    titleTh: 'วิทยาศาสตร์ฉลาดรู้ในยุคดิจิทัลเพื่อพัฒนาที่ยั่งยืน',
    titleEn: 'Scientific Literacy in the Digital Era for Sustainable Development',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10400501',
    titleTh: 'นานาสาระเกี่ยวกับอาหารและยา',
    titleEn: 'General Aspects of Food and Drug',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700501',
    titleTh: 'การรู้สารสนเทศและการใช้สื่อดิจิทัลเพื่อการเรียนรู้และการดำรงชีวิต',
    titleEn: 'Information Literacy and Digital Media for Lifelong Learning',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700502',
    titleTh: 'ความฉลาดรู้ดิจิทัลเพื่อการพัฒนาตน',
    titleEn: 'Digital Intelligent for Self-Development',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 2,
    labHours: 2,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10700503',
    titleTh: 'จิตวิทยาสำหรับผู้เรียนรู้ตลอดชีวิต',
    titleEn: 'Psychology for Lifelong Learner',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10700504',
    titleTh: 'สุขภาวะองค์รวม 360 องศา',
    titleEn: '360° Wellness',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10800501',
    titleTh: 'สื่อสร้างสรรค์เพื่อการเกษตร',
    titleEn: 'Creative Media for Agriculture',
    description: 'หมวดวิชาศึกษาทั่วไป สมรรถนะด้านการทำงานและการเรียนรู้ตลอดชีวิต',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },

  // --- หมวดวิชาเฉพาะ: วิชาแกน (หลักสูตร 2570) ---
  {
    code: '10301111-68',
    titleTh: 'พื้นฐานการเขียนโปรแกรม',
    titleEn: 'Fundamentals of Programming',
    description: 'วิชาแกน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301112-68',
    titleTh: 'เทคโนโลยีสารสนเทศและการสื่อสาร',
    titleEn: 'Information and Communication Technology (ICT)',
    description: 'วิชาแกน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301113-68',
    titleTh: 'คณิตศาสตร์ดีสครีต',
    titleEn: 'Discrete Mathematics',
    description: 'วิชาแกน หลักสูตร 2570',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301115',
    titleTh: 'คณิตศาสตร์สำหรับวิทยาการคอมพิวเตอร์',
    titleEn: 'Mathematics for Computer Science',
    description: 'วิชาแกน หลักสูตร 2570',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301211-68',
    titleTh: 'หลักการเขียนโปรแกรมเชิงวัตถุ',
    titleEn: 'Principles of Object-Oriented Programming',
    description: 'วิชาแกน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10355205',
    titleTh: 'ความน่าจะเป็นและสถิติ',
    titleEn: 'Probability and Statistics',
    description: 'วิชาแกน หลักสูตร 2570',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },

  // --- หมวดวิชาเฉพาะ: วิชาเฉพาะด้าน (หลักสูตร 2570) ---
  {
    code: '10301114-68',
    titleTh: 'องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์',
    titleEn: 'Computer Organization and Architecture',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301141-68',
    titleTh: 'การพัฒนาเว็บแอปพลิเคชัน',
    titleEn: 'Web Application Development',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301151',
    titleTh: 'เครือข่ายคอมพิวเตอร์เบื้องต้น',
    titleEn: 'Computer Networks',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301221-68',
    titleTh: 'โครงสร้างข้อมูลและอัลกอริทึม',
    titleEn: 'Data Structures and Algorithms',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301222-68',
    titleTh: 'ระบบฐานข้อมูล',
    titleEn: 'Database Systems',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301223-68',
    titleTh: 'การวิเคราะห์และออกแบบเชิงวัตถุ',
    titleEn: 'Object-Oriented Analysis and Design',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301231-68',
    titleTh: 'ปัญญาประดิษฐ์',
    titleEn: 'Artificial Intelligence',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301241',
    titleTh: 'วิศวกรรมระบบฝั่งเซิร์ฟเวอร์',
    titleEn: 'Server-Side System Engineering',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301242',
    titleTh: 'การพัฒนาซอฟต์แวร์บนอุปกรณ์เคลื่อนที่',
    titleEn: 'Mobile Application Development',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301243',
    titleTh: 'การพัฒนาและการปฏิบัติการ',
    titleEn: 'DevOps & CICD',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301311-68',
    titleTh: 'ทักษะการเขียนโปรแกรมและการแก้ปัญหา',
    titleEn: 'Programming and Problem-Solving Skills',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301330',
    titleTh: 'วิศวกรรมและธรรมาภิบาลข้อมูล',
    titleEn: 'Data Engineering and Governance',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301461',
    titleTh: 'สัมมนาวิชาการทางวิทยาการคอมพิวเตอร์',
    titleEn: 'Seminar for Computer Science',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 3,
    lectureHours: 3,
    labHours: 0,
    selfStudyHours: 6,
    isActive: true,
  },
  {
    code: '10301497',
    titleTh: 'สหกิจศึกษา',
    titleEn: 'Co-Operative Education',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 6,
    lectureHours: 0,
    labHours: 0,
    selfStudyHours: 0,
    isActive: true,
  },
  {
    code: '10301498',
    titleTh: 'การเรียนรู้อิสระ',
    titleEn: 'Independent Study',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 6,
    lectureHours: 0,
    labHours: 0,
    selfStudyHours: 0,
    isActive: true,
  },
  {
    code: '10301499',
    titleTh: 'การศึกษา หรือ ฝึกงาน หรือ ฝึกอบรมต่างประเทศ',
    titleEn: 'Overseas Study, Training or Internship',
    description: 'วิชาเฉพาะด้าน หลักสูตร 2570',
    credits: 6,
    lectureHours: 0,
    labHours: 0,
    selfStudyHours: 0,
    isActive: true,
  },

  // --- วิชาพื้นฐานวิชาชีพและวิชาชีพ: กลุ่ม AI & Data Science ---
  {
    code: '10301331-68',
    titleTh: 'พื้นฐานวิทยาการข้อมูล',
    titleEn: 'Fundamental of Data Science',
    description: 'กลุ่มวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล (AI & Data Science)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301332-68',
    titleTh: 'การประมวลผลเชิงภาพ',
    titleEn: 'Digital Image Processing',
    description: 'กลุ่มวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล (AI & Data Science)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301333-68',
    titleTh: 'การประมวลผลภาษาธรรมชาติสมัยใหม่',
    titleEn: 'Modern Natural Language Processing',
    description: 'กลุ่มวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล (AI & Data Science)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301334-68',
    titleTh: 'การแยกแยะและการแบ่งกลุ่มข้อมูล',
    titleEn: 'Data Classification and Clustering',
    description: 'กลุ่มวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล (AI & Data Science)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301335-68',
    titleTh: 'การเรียนรู้ของเครื่องจักร',
    titleEn: 'Machine Learning',
    description: 'กลุ่มวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล (AI & Data Science)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301336-68',
    titleTh: 'คอมพิวเตอร์วิทัศน์',
    titleEn: 'Computer Vision',
    description: 'กลุ่มวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล (AI & Data Science)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301337',
    titleTh: 'ปัญญาประดิษฐ์สร้างสรรค์และการออกแบบคำสั่ง',
    titleEn: 'Generative Artificial Intelligence and Prompt Engineering',
    description: 'กลุ่มวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล (AI & Data Science)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301338',
    titleTh: 'ปัญญาประดิษฐ์เพื่อสุขภาวะที่ยั่งยืน',
    titleEn: 'Artificial Intelligence for Sustainable Well-being',
    description: 'กลุ่มวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล (AI & Data Science)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301339',
    titleTh: 'เครื่องมือและการประยุกต์ใช้การเล่าเรื่องข้อมูล',
    titleEn: 'Tools and Applications for Data Storytelling',
    description: 'กลุ่มวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล (AI & Data Science)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },

  // --- วิชาพื้นฐานวิชาชีพและวิชาชีพ: กลุ่ม Software Engineering & Digital Innovation ---
  {
    code: '10301341-68',
    titleTh: 'วิศวกรรมซอฟต์แวร์และการเข้าถึง',
    titleEn: 'Software Engineering and Accessibility',
    description: 'กลุ่มวิชาวิศวกรรมซอฟต์แวร์และนวัตกรรมดิจิทัล (Software Engineering & Digital Innovation)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301342-68',
    titleTh: 'การพัฒนาแอปพลิเคชันเชิงสร้างสรรค์ข้ามแพลตฟอร์ม',
    titleEn: 'Creative Cross-Platform Application Development',
    description: 'กลุ่มวิชาวิศวกรรมซอฟต์แวร์และนวัตกรรมดิจิทัล (Software Engineering & Digital Innovation)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301343-68',
    titleTh: 'การพัฒนามัลติมีเดียและเกม',
    titleEn: 'Multimedia and Game Development',
    description: 'กลุ่มวิชาวิศวกรรมซอฟต์แวร์และนวัตกรรมดิจิทัล (Software Engineering & Digital Innovation)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301344-68',
    titleTh: 'การพัฒนาซอฟต์แวร์การซื้อขายอัตโนมัติ',
    titleEn: 'Automated Trading Software Development',
    description: 'กลุ่มวิชาวิศวกรรมซอฟต์แวร์และนวัตกรรมดิจิทัล (Software Engineering & Digital Innovation)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301345-68',
    titleTh: 'การพัฒนาซอฟต์แวร์สำหรับการซื้อขายความถี่สูง',
    titleEn: 'High Frequency Trading Software Development',
    description: 'กลุ่มวิชาวิศวกรรมซอฟต์แวร์และนวัตกรรมดิจิทัล (Software Engineering & Digital Innovation)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301346-68',
    titleTh: 'ธุรกิจอัจฉริยะ',
    titleEn: 'Business Intelligence',
    description: 'กลุ่มวิชาวิศวกรรมซอฟต์แวร์และนวัตกรรมดิจิทัล (Software Engineering & Digital Innovation)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301347-68',
    titleTh: 'ระบบสารสนเทศเพื่อการจัดการ',
    titleEn: 'Management Information System',
    description: 'กลุ่มวิชาวิศวกรรมซอฟต์แวร์และนวัตกรรมดิจิทัล (Software Engineering & Digital Innovation)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301348',
    titleTh: 'บล็อกเชน และคริปโทเคอร์เรนซี่',
    titleEn: 'Blockchain and Cryptocurrency',
    description: 'กลุ่มวิชาวิศวกรรมซอฟต์แวร์และนวัตกรรมดิจิทัล (Software Engineering & Digital Innovation)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301349',
    titleTh: 'ฟินเทคและการวิเคราะห์ข้อมูลขนาดใหญ่',
    titleEn: 'FinTech and Big Data Analytics',
    description: 'กลุ่มวิชาวิศวกรรมซอฟต์แวร์และนวัตกรรมดิจิทัล (Software Engineering & Digital Innovation)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },

  // --- วิชาพื้นฐานวิชาชีพและวิชาชีพ: กลุ่ม Digital Infrastructure & Emerging Technologies ---
  {
    code: '10301351-68',
    titleTh: 'การประมวลผลแบบกลุ่มเมฆ',
    titleEn: 'Cloud Computing',
    description: 'กลุ่มวิชาโครงสร้างพื้นฐานดิจิทัลและเทคโนโลยีล้ำสมัย (Digital Infrastructure & Emerging Technologies)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301352-68',
    titleTh: 'อินเทอร์เน็ตในทุกสิ่ง',
    titleEn: 'Internet of Things',
    description: 'กลุ่มวิชาโครงสร้างพื้นฐานดิจิทัลและเทคโนโลยีล้ำสมัย (Digital Infrastructure & Emerging Technologies)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301353-68',
    titleTh: 'ตรรกศาสตร์เชิงดิจิทัลและอุปกรณ์อัจฉริยะ',
    titleEn: 'Digital Logic and Intelligent Devices',
    description: 'กลุ่มวิชาโครงสร้างพื้นฐานดิจิทัลและเทคโนโลยีล้ำสมัย (Digital Infrastructure & Emerging Technologies)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301354-68',
    titleTh: 'ความมั่นคงปลอดภัยไซเบอร์',
    titleEn: 'Cybersecurity',
    description: 'กลุ่มวิชาโครงสร้างพื้นฐานดิจิทัลและเทคโนโลยีล้ำสมัย (Digital Infrastructure & Emerging Technologies)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301355-68',
    titleTh: 'การประมวลผลเชิงควอนตัม',
    titleEn: 'Quantum Computing',
    description: 'กลุ่มวิชาโครงสร้างพื้นฐานดิจิทัลและเทคโนโลยีล้ำสมัย (Digital Infrastructure & Emerging Technologies)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301356-68',
    titleTh: 'การประมวลผลสัญญาณดิจิทัล',
    titleEn: 'Digital Signal Processing',
    description: 'กลุ่มวิชาโครงสร้างพื้นฐานดิจิทัลและเทคโนโลยีล้ำสมัย (Digital Infrastructure & Emerging Technologies)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301357-68',
    titleTh: 'วิศวกรรมเครือข่ายคอมพิวเตอร์',
    titleEn: 'Computer Network Engineering',
    description: 'กลุ่มวิชาโครงสร้างพื้นฐานดิจิทัลและเทคโนโลยีล้ำสมัย (Digital Infrastructure & Emerging Technologies)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },

  // --- วิชาพื้นฐานวิชาชีพและวิชาชีพ: กลุ่มหัวข้อพิเศษ ---
  {
    code: '10301361-68',
    titleTh: 'หัวข้อพิเศษทางวิทยาการคอมพิวเตอร์ 1',
    titleEn: 'Special Topics in Computer Science 1',
    description: 'กลุ่มวิชาหัวข้อพิเศษ (Special Topics)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
  {
    code: '10301362-68',
    titleTh: 'หัวข้อพิเศษทางวิทยาการคอมพิวเตอร์ 2',
    titleEn: 'Special Topics in Computer Science 2',
    description: 'กลุ่มวิชาหัวข้อพิเศษ (Special Topics)',
    credits: 3,
    lectureHours: 2,
    labHours: 3,
    selfStudyHours: 5,
    isActive: true,
  },
];
